<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ace</string>
	</array>
	<key>name</key>
	<string>Ace (Ruby Host)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#firstSection</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>firstSection</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%%</string>
					<key>end</key>
					<string>a^</string>
					<key>name</key>
					<string>meta.section.third.ace.ruby</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#secondSection</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(%[A-Za-z0-9_.-]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.ace.ruby</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>meta.function.ace.ruby</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(&lt;)((?:\\&gt;|[^&gt;])*)(&gt;)</string>
							<key>name</key>
							<string>string.quoted.other.ace.ruby</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\{)((?:\\}|[^}])*)(\})</string>
							<key>name</key>
							<string>string.quoted.other.ace.ruby</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\')((?:\\'|[^'])*)(\')</string>
							<key>name</key>
							<string>string.quoted.single.ace.ruby</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\")((?:\\"|[^"])*)(\")</string>
							<key>name</key>
							<string>string.quoted.double.ace.ruby</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;=\s)([A-Za-z0-9_.-]+)(?=\s)</string>
							<key>name</key>
							<string>variable.parameter.ace.ruby</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>secondSection</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%%</string>
					<key>end</key>
					<string>a^</string>
					<key>name</key>
					<string>meta.section.last.ace.ruby</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9._-]+:</string>
					<key>name</key>
					<string>constant.other.symbol.ace.ruby</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)[A-Z]+(?=\s)</string>
					<key>name</key>
					<string>variable.other.constant.ace.ruby</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>keyword.operator.ace.ruby</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>thirdSection</key>
		<dict>
			<key>patterns</key>
			<array/>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ace.ruby</string>
	<key>uuid</key>
	<string>2d7fd617-f324-4476-9380-f5108efdf88d</string>
</dict>
</plist>
